apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s-manifests
    repoURL: https://github.com/apthagowda97/python-helloworld
    targetRevision: HEAD
  syncPolicy: {}