apiVersion: v1
kind: Service
metadata:
  name: python-helloword-svc
  labels:
    app: python-helloword-app
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: python-helloword-app
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
